// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// deconv_dct_multi
Rcpp::List deconv_dct_multi(const arma::mat& Y, const arma::vec& h, const int K, Rcpp::Nullable<Rcpp::NumericVector> q_in, const std::string method, const double lambda_fixed, const int ngrid, const double lam_lo, const double lam_hi);
RcppExport SEXP _multiPPI_deconv_dct_multi(SEXP YSEXP, SEXP hSEXP, SEXP KSEXP, SEXP q_inSEXP, SEXP methodSEXP, SEXP lambda_fixedSEXP, SEXP ngridSEXP, SEXP lam_loSEXP, SEXP lam_hiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type h(hSEXP);
    Rcpp::traits::input_parameter< const int >::type K(KSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type q_in(q_inSEXP);
    Rcpp::traits::input_parameter< const std::string >::type method(methodSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda_fixed(lambda_fixedSEXP);
    Rcpp::traits::input_parameter< const int >::type ngrid(ngridSEXP);
    Rcpp::traits::input_parameter< const double >::type lam_lo(lam_loSEXP);
    Rcpp::traits::input_parameter< const double >::type lam_hi(lam_hiSEXP);
    rcpp_result_gen = Rcpp::wrap(deconv_dct_multi(Y, h, K, q_in, method, lambda_fixed, ngrid, lam_lo, lam_hi));
    return rcpp_result_gen;
END_RCPP
}
// mppi_deconv_map
arma::mat mppi_deconv_map(const arma::mat& Y, const arma::vec& h, const double lambda);
RcppExport SEXP _multiPPI_mppi_deconv_map(SEXP YSEXP, SEXP hSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type h(hSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(mppi_deconv_map(Y, h, lambda));
    return rcpp_result_gen;
END_RCPP
}
// ewm_gated_cross_rcpp
List ewm_gated_cross_rcpp(NumericMatrix U, NumericMatrix PK, double eta, IntegerVector offsets, bool normalized, IntegerVector blocklens);
RcppExport SEXP _multiPPI_ewm_gated_cross_rcpp(SEXP USEXP, SEXP PKSEXP, SEXP etaSEXP, SEXP offsetsSEXP, SEXP normalizedSEXP, SEXP blocklensSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type U(USEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type PK(PKSEXP);
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type offsets(offsetsSEXP);
    Rcpp::traits::input_parameter< bool >::type normalized(normalizedSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type blocklens(blocklensSEXP);
    rcpp_result_gen = Rcpp::wrap(ewm_gated_cross_rcpp(U, PK, eta, offsets, normalized, blocklens));
    return rcpp_result_gen;
END_RCPP
}
// inst_corr_rcpp
NumericVector inst_corr_rcpp(NumericVector x, NumericVector y, double tau_half, int offset, int warmup, std::string fill);
RcppExport SEXP _multiPPI_inst_corr_rcpp(SEXP xSEXP, SEXP ySEXP, SEXP tau_halfSEXP, SEXP offsetSEXP, SEXP warmupSEXP, SEXP fillSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type tau_half(tau_halfSEXP);
    Rcpp::traits::input_parameter< int >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< int >::type warmup(warmupSEXP);
    Rcpp::traits::input_parameter< std::string >::type fill(fillSEXP);
    rcpp_result_gen = Rcpp::wrap(inst_corr_rcpp(x, y, tau_half, offset, warmup, fill));
    return rcpp_result_gen;
END_RCPP
}
// ppi_batch_cpp
SEXP ppi_batch_cpp(const arma::mat& U, const arma::mat& G, const IntegerVector& lags, const IntegerVector& blocklens);
RcppExport SEXP _multiPPI_ppi_batch_cpp(SEXP USEXP, SEXP GSEXP, SEXP lagsSEXP, SEXP blocklensSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type U(USEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type G(GSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type lags(lagsSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type blocklens(blocklensSEXP);
    rcpp_result_gen = Rcpp::wrap(ppi_batch_cpp(U, G, lags, blocklens));
    return rcpp_result_gen;
END_RCPP
}
// ridge_precision_cpp
arma::mat ridge_precision_cpp(const arma::mat& S, double lambda);
RcppExport SEXP _multiPPI_ridge_precision_cpp(SEXP SSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type S(SSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(ridge_precision_cpp(S, lambda));
    return rcpp_result_gen;
END_RCPP
}
// precision_gate_cpp
arma::cube precision_gate_cpp(const arma::mat& Theta0, const arma::cube& M);
RcppExport SEXP _multiPPI_precision_gate_cpp(SEXP Theta0SEXP, SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Theta0(Theta0SEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(precision_gate_cpp(Theta0, M));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_multiPPI_deconv_dct_multi", (DL_FUNC) &_multiPPI_deconv_dct_multi, 9},
    {"_multiPPI_mppi_deconv_map", (DL_FUNC) &_multiPPI_mppi_deconv_map, 3},
    {"_multiPPI_ewm_gated_cross_rcpp", (DL_FUNC) &_multiPPI_ewm_gated_cross_rcpp, 6},
    {"_multiPPI_inst_corr_rcpp", (DL_FUNC) &_multiPPI_inst_corr_rcpp, 6},
    {"_multiPPI_ppi_batch_cpp", (DL_FUNC) &_multiPPI_ppi_batch_cpp, 4},
    {"_multiPPI_ridge_precision_cpp", (DL_FUNC) &_multiPPI_ridge_precision_cpp, 2},
    {"_multiPPI_precision_gate_cpp", (DL_FUNC) &_multiPPI_precision_gate_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_multiPPI(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
