# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

deconv_dct_multi <- function(Y, h, K = 64L, q_in = NULL, method = "gcv", lambda_fixed = 1e-1, ngrid = 30L, lam_lo = 1e-6, lam_hi = 1e+6) {
    .Call(`_multiPPI_deconv_dct_multi`, Y, h, K, q_in, method, lambda_fixed, ngrid, lam_lo, lam_hi)
}

mppi_deconv_map <- function(Y, h, lambda) {
    .Call(`_multiPPI_mppi_deconv_map`, Y, h, lambda)
}

