# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

deconv_dct_multi <- function(Y, h, K = 64L, q_in = NULL, method = "gcv", lambda_fixed = 1e-1, ngrid = 30L, lam_lo = 1e-6, lam_hi = 1e+6) {
    .Call(`_multiPPI_deconv_dct_multi`, Y, h, K, q_in, method, lambda_fixed, ngrid, lam_lo, lam_hi)
}

mppi_deconv_map <- function(Y, h, lambda) {
    .Call(`_multiPPI_mppi_deconv_map`, Y, h, lambda)
}

ewm_gated_cross_rcpp <- function(U, PK, eta, offsets, normalized = TRUE, blocklens = integer()) {
    .Call(`_multiPPI_ewm_gated_cross_rcpp`, U, PK, eta, offsets, normalized, blocklens)
}

inst_corr_rcpp <- function(x, y, tau_half, offset = 0L, warmup = -1L, fill = "zero") {
    .Call(`_multiPPI_inst_corr_rcpp`, x, y, tau_half, offset, warmup, fill)
}

ppi_batch_cpp <- function(U, G, lags, blocklens = integer()) {
    .Call(`_multiPPI_ppi_batch_cpp`, U, G, lags, blocklens)
}

ridge_precision_cpp <- function(S, lambda) {
    .Call(`_multiPPI_ridge_precision_cpp`, S, lambda)
}

precision_gate_cpp <- function(Theta0, M) {
    .Call(`_multiPPI_precision_gate_cpp`, Theta0, M)
}

